<h1 id="13-1-错误处理"><a href="#13-1-错误处理" class="headerlink" title="13.1 错误处理"></a>13.1 错误处理</h1><p>Go 有一个预先定义的 error 接口类型</p>
<pre><code class="go"><span class="keyword">type</span> error <span class="keyword">interface</span> {
    Error() <span class="keyword">string</span>
}</code></pre>
<p>错误值用来表示异常状态；我们可以在 <a href="05.2.md">5.2 节</a>中看到它的标准用法。处理文件操作的例子可以在 12 章找到；我们将在 15 章看到网络操作的例子。errors 包中有一个 errorString 结构体实现了 error 接口。当程序处于错误状态时可以用 <code>os.Exit(1)</code> 来中止运行。</p>
<h2 id="13-1-1-定义错误"><a href="#13-1-1-定义错误" class="headerlink" title="13.1.1 定义错误"></a>13.1.1 定义错误</h2><p>任何时候当你需要一个新的错误类型，都可以用 <code>errors</code>（必须先 import）包的 <code>errors.New</code> 函数接收合适的错误信息来创建，像下面这样：</p>
<pre><code class="go">err := errors.New(“math - square root of negative number”)</code></pre>
<p>在示例 13.1 中你可以看到一个简单的用例：</p>
<p>示例 13.1 <a href="examples/chapter_13/errors.go">errors.go</a>：</p>
<pre><code class="go"><span class="comment">// errors.go</span>
<span class="keyword">package</span> main

<span class="keyword">import</span> (
    <span class="string">"errors"</span>
    <span class="string">"fmt"</span>
)

<span class="keyword">var</span> errNotFound error = errors.New(<span class="string">"Not found error"</span>)

<span class="function"><span class="keyword">func</span> <span class="title">main</span><span class="params">()</span></span> {
    fmt.Printf(<span class="string">"error: %v"</span>, errNotFound)
}
<span class="comment">// error: Not found error</span></code></pre>
<p>可以把它用于计算平方根函数的参数测试：</p>
<pre><code class="go"><span class="function"><span class="keyword">func</span> <span class="title">Sqrt</span><span class="params">(f <span class="keyword">float64</span>)</span> <span class="params">(<span class="keyword">float64</span>, error)</span></span> {
    <span class="keyword">if</span> f &lt; <span class="number">0</span> {
        <span class="keyword">return</span> <span class="number">0</span>, errors.New (<span class="string">"math - square root of negative number"</span>)
    }
   <span class="comment">// implementation of Sqrt</span>
}</code></pre>
<p>你可以像下面这样调用 Sqrt 函数：</p>
<pre><code class="go"><span class="keyword">if</span> f, err := Sqrt(<span class="number">-1</span>); err != <span class="literal">nil</span> {
    fmt.Printf(<span class="string">"Error: %s\n"</span>, err)
}</code></pre>
<p>由于 <code>fmt.Printf</code> 会自动调用 <code>String()</code> 方法 （参见 <a href="10.7.md">10.7 节</a>），所以错误信息 “Error: math - square root of negative number” 会打印出来。通常（错误信息）都会有像 “Error:” 这样的前缀，所以你的错误信息不要以大写字母开头。</p>
<p>在大部分情况下自定义错误结构类型很有意义的，可以包含除了（低层级的）错误信息以外的其它有用信息，例如，正在进行的操作（打开文件等），全路径或名字。看下面例子中 os.Open 操作触发的 PathError 错误：</p>
<pre><code class="go"><span class="comment">// PathError records an error and the operation and file path that caused it.</span>
<span class="keyword">type</span> PathError <span class="keyword">struct</span> {
    Op <span class="keyword">string</span>    <span class="comment">// "open", "unlink", etc.</span>
    Path <span class="keyword">string</span>  <span class="comment">// The associated file.</span>
    Err error  <span class="comment">// Returned by the system call.</span>
}

<span class="function"><span class="keyword">func</span> <span class="params">(e *PathError)</span> <span class="title">String</span><span class="params">()</span> <span class="title">string</span></span> {
    <span class="keyword">return</span> e.Op + <span class="string">" "</span> + e.Path + <span class="string">": "</span>+ e.Err.Error()
}</code></pre>
<p>如果有不同错误条件可能发生，那么对实际的错误使用类型断言或类型判断（type-switch）是很有用的，并且可以根据错误场景做一些补救和恢复操作。</p>
<pre><code class="go"><span class="comment">//  err != nil</span>
<span class="keyword">if</span> e, ok := err.(*os.PathError); ok {
    <span class="comment">// remedy situation</span>
}</code></pre>
<p>或：</p>
<pre><code class="go"><span class="keyword">switch</span> err := err.(<span class="keyword">type</span>) {
    <span class="keyword">case</span> ParseError:
        PrintParseError(err)
    <span class="keyword">case</span> PathError:
        PrintPathError(err)
    ...
    <span class="keyword">default</span>:
        fmt.Printf(<span class="string">"Not a special error, just %s\n"</span>, err)
}</code></pre>
<p>作为第二个例子考虑用 json 包的情况。当 json.Decode 在解析 JSON 文档发生语法错误时，指定返回一个 SyntaxError 类型的错误：</p>
<pre><code class="go"><span class="keyword">type</span> SyntaxError <span class="keyword">struct</span> {
    msg    <span class="keyword">string</span> <span class="comment">// description of error</span>
<span class="comment">// error occurred after reading Offset bytes, from which line and columnnr can be obtained</span>
    Offset <span class="keyword">int64</span>
}

<span class="function"><span class="keyword">func</span> <span class="params">(e *SyntaxError)</span> <span class="title">String</span><span class="params">()</span> <span class="title">string</span></span> { <span class="keyword">return</span> e.msg }</code></pre>
<p>在调用代码中你可以像这样用类型断言测试错误是不是上面的类型：</p>
<pre><code class="go"><span class="keyword">if</span> serr, ok := err.(*json.SyntaxError); ok {
    line, col := findLine(f, serr.Offset)
    <span class="keyword">return</span> fmt.Errorf(<span class="string">"%s:%d:%d: %v"</span>, f.Name(), line, col, err)
}</code></pre>
<p>包也可以用额外的方法（methods）定义特定的错误，比如 net.Error：</p>
<pre><code class="go"><span class="keyword">package</span> net
<span class="keyword">type</span> Error <span class="keyword">interface</span> {
    Timeout() <span class="keyword">bool</span>   <span class="comment">// Is the error a timeout?</span>
    Temporary() <span class="keyword">bool</span> <span class="comment">// Is the error temporary?</span>
}</code></pre>
<p>在 <a href="15.1.md">15.1 节</a> 我们可以看到怎么使用它。</p>
<p>正如你所看到的一样，所有的例子都遵循同一种命名规范：错误类型以 “Error” 结尾，错误变量以 “err” 或 “Err” 开头。</p>
<p>syscall 是低阶外部包，用来提供系统基本调用的原始接口。它们返回整数的错误码；类型 syscall.Errno 实现了 Error 接口。</p>
<p>大部分 syscall 函数都返回一个结果和可能的错误，比如：</p>
<pre><code class="go">r, err := syscall.Open(name, mode, perm)
<span class="keyword">if</span> err != <span class="number">0</span> {
    fmt.Println(err.Error())
}</code></pre>
<p>os 包也提供了一套像 os.EINAL 这样的标准错误，它们基于 syscall 错误：</p>
<pre><code class="go"><span class="keyword">var</span> (
    EPERM        Error = Errno(syscall.EPERM)
    ENOENT        Error = Errno(syscall.ENOENT)
    ESRCH        Error = Errno(syscall.ESRCH)
    EINTR        Error = Errno(syscall.EINTR)
    EIO            Error = Errno(syscall.EIO)
    ...
)</code></pre>
<h2 id="13-1-2-用-fmt-创建错误对象"><a href="#13-1-2-用-fmt-创建错误对象" class="headerlink" title="13.1.2 用 fmt 创建错误对象"></a>13.1.2 用 fmt 创建错误对象</h2><p>通常你想要返回包含错误参数的更有信息量的字符串，例如：可以用 <code>fmt.Errorf()</code> 来实现：它和 fmt.Printf() 完全一样，接收有一个或多个格式占位符的格式化字符串和相应数量的占位变量。和打印信息不同的是它用信息生成错误对象。</p>
<p>比如在前面的平方根例子中使用：</p>
<pre><code class="go"><span class="keyword">if</span> f &lt; <span class="number">0</span> {
    <span class="keyword">return</span> <span class="number">0</span>, fmt.Errorf(<span class="string">"math: square root of negative number %g"</span>, f)
}</code></pre>
<p>第二个例子：从命令行读取输入时，如果加了 help 标志，我们可以用有用的信息产生一个错误：</p>
<pre><code class="go"><span class="keyword">if</span> <span class="built_in">len</span>(os.Args) &gt; <span class="number">1</span> &amp;&amp; (os.Args[<span class="number">1</span>] == <span class="string">"-h"</span> || os.Args[<span class="number">1</span>] == <span class="string">"--help"</span>) {
    err = fmt.Errorf(<span class="string">"usage: %s infile.txt outfile.txt"</span>, filepath.Base(os.Args[<span class="number">0</span>]))
    <span class="keyword">return</span>
}</code></pre>
<h2 id="链接"><a href="#链接" class="headerlink" title="链接"></a>链接</h2><ul>
<li><a href="directory.md">目录</a></li>
<li>上一节：<a href="13.0.md">错误处理与测试</a></li>
<li>下一节：<a href="13.2.md">运行时异常和 panic</a></li>
</ul>
